### ISSUE TITLE
Chapter 1: Perkenalan Pemrograman Kompetitif, A. Seleksi Olimpiade

### ISSUE THREAD

**Issue by fariskhi** [ia-toki/training-gate-id#103]
Halo,

Pada soal 'Seleksi Olimpiade' tertulis

> Dijamin tidak ada dua ID peserta yang identik pada suatu seleksi dan **tidak ada dua peserta yang memperoleh nilai yang persis sama untuk semua sesi.**

Saya mencoba untuk meng-TLE-kan program saya ketika ada dua peserta yang nilainya persis sama untuk semua sesi dan hasilnya Time Limit Exceeded.

Hal ini akan membuat pengguna yang mencoba menyelesaikan soal ini dengan sorting bisa tidak mendapatkan 100. Seperti pada salah satu submission yang saya coba.

Terima kasih.

**Comment by gyosh** [comment]
@fariskhi Bisa minta nomor id submission yg TLE itu?
Cek di URL halaman hasil gradingnya

**Comment by gyosh** [comment]
TC yang cacat sudah dihapus
Terima kasih atas laporannya
