### ISSUE TITLE
OSN Informatika 2010 - Hari 2 Keluarga Bebek dan Berat Bebek

### ISSUE THREAD

**Issue by killoys99** [ia-toki/training-gate-id#105]
Di dua soal ini nilai maksimumnya cuma 91 padahal algonya  submit di tlc ac (100) buktinya gak ada orang yang  ac pada dua soal itu

**Comment by killoys99** [comment]
sama yang melukis OSN Informatika 2010 hari 2 contoh input soalnya salah gak kaya tlc

**Comment by gyosh** [comment]
@killoys99: Ini kenapa di-close ya?
Apakah isunya tidak jadi diajukan?

**Comment by killoys99** [comment]
sudah ac yang Keluarga Bebek sudah diperbaiki dan yang Berat Bebek sudah ac mungkin tc nya di tlx beda sama tlc tapi sudah bener
tapi yang melukis OSN Informatika 2010 hari 2 contoh input soalnya salah gak kaya tlc

**Comment by gyosh** [comment]
Baiklah.
Soal melukis sudah diperbaiki contoh kasusnya. Sepertinya ketika migrasi terjadi duplikasi contoh masukan.

Terima kasih atas laporannya.
