### ISSUE TITLE
 Ada Kemungkinan Salah Test Case Chapter 1C: Perulangan  H. Faktor Bilangan

### ISSUE THREAD

**Issue by mhazim2** [ia-toki/training-gate-id#106]
Saya sdh coba pakai C & C++ tdk accept
Tp teman pakai pascal accept
padahal outputnya sama...

Ada yang bisa bantu ??? ^_^

**Comment by gyosh** [comment]
Yakin solusi yg ditulis di C & C++ sama dengan yg di Pascal?
Output sama untuk beberapa kasus belum berarti keduanya sama-sama solusi yg benar...

Kemungkinan besar testcase tidak bermasalah.
Bisa cantumkan solusi kamu?

**Comment by mhazim2** [comment]
#include <bits/stdc++.h>
using namespace std;
int main()
{
    int N,cnt=1,mod,out;
    scanf("%d",&N);
    while(out){
        mod=N%cnt;
        out=N/cnt++;
        if(mod==0) printf("%d\n",out);
    }
    return 0;
}

**Comment by mhazim2** [comment]
terimasih sebelumnya...

**Comment by gyosh** [comment]
@mhazim2 Maaf saya baru melihat kembali isu ini
Kode kamu bisa bermasalah kalo dijalankan di mesin lain, karena variabel `out` tidak diinisialisasi.
Di grader,`while (out)` langsung bernilai false sehingga kode di bagian dalam while sama sekali tidak dijalankan.
