### ISSUE TITLE
TLC Bab 4D : Rotasi Matriks

### ISSUE THREAD

**Issue by Ngiong** [ia-toki/training-gate-id#107]
Sepertinya ada kemungkinan salah TC di soal tsb, karena saya menggunakan solusi saya yang sudah AC 100 di TLC, namun mendapat nilai hanya 67. Dan belum ada submission yang berhasil memperoleh nilai 100 untuk soal tsb. Terima kasih sebelumnya.

**Comment by gyosh** [comment]
Sepertinya Anda benar
Akan diperbaiki secepatnya

**Comment by gyosh** [comment]
Sudah diperbaiki.
Terima kasih atas laporannya.
