### ISSUE TITLE
bab 10 b tlx

### ISSUE THREAD

**Issue by platyunyu** [ia-toki/training-gate-id#108]
kyknya ada yang salah 3 tc trakhir selalu salah

**Comment by gyosh** [comment]
@platyunyu Bisa minta beberapa submission ID kamu yg bikin 3 tc itu salah?

**Comment by gyosh** [comment]
@platyunyu Tidak ditemukan masalah pada kasus uji.
Mohon memberikan submission ID kamu yg buat 3 kasus uji itu salah, dalam kurun waktu 3 hari, atau isu ditutup.

**Comment by gyosh** [comment]
Karena tidak ada jawaban, untuk kali ini isu ditutup.
