### ISSUE TITLE
PDF on Releases

### ISSUE THREAD

**Issue by petrabarus** [ia-toki/training-gate-id#109]
Just curious, instead of creating new repo, why don't you guys use the releases for PDF?

**Comment by alijaya** [comment]
eh new repo? what? ._.

**Comment by fushar** [comment]
We need raw .pdf blob files to be rendered on the courses, which I believe can't be provided from Releases.

**Comment by gyosh** [comment]
I consider to mark this issue as resolved within next 48 hours, unless @petrabarus reply something else
