### ISSUE TITLE
Makefile sebagai build script

### ISSUE THREAD

**Issue by fushar** [ia-toki/training-gate-id#11]
Referensi: https://tex.stackexchange.com/questions/40738/how-to-properly-make-a-latex-project

**Comment by petrabarus** [comment]
+1

**Comment by gyosh** [comment]
@fushar bolehkah dibuat bash script yang di dalamnya memanggil make?
Karena makefile sulit dikonfigurasi untuk bisa masuk ke direktori yang berbeda-beda

**Comment by fushar** [comment]
@gyosh sejauh ini udah jadi kayak apa?

**Comment by gyosh** [comment]
@fushar kurang lebih:

  SRC=$(wildcard ./*/*/materi/*.tex)
  
  all: $(SRC)
  	latexmk -pdf -pdflatex="pdflatex -interactive=nonstopmode" -use-make $?
  
  clean: 
  	latexmk -C

makefile itu ditempatkan di folder root, jadi harapannya kalau ada ./pemrograman-dasar/1-perkenalan/materi/materi1.tex diupdate, dia bakal di-build ulang.
Sayangnya ini belum bekerja karena ketika latexmk dijalankan, seluruh file assets/image.png yg ada di butuhkan materi1.tex harus ada di lokasi makefile berada (yaitu root), padahal adanya di ./pemrograman-dasar/1-perkenalan/materi/asset. Jadi dia gak bisa akses asset2nya.

Solusinya sebenarnya bisa pakai argumen tambahan pada latexmk: -auxdir="path/to/asset".
Cuman kita butuh "path/to/asset", yang sulit didapatkan kalau pake makefile.

Jadi idenya sih pakai bash script lama untuk list semua file .tex, lalu masing-masing di-make. Kan kalau bash script cari "path/to/asset" bisa pakai tokenisasi dsb.

**Comment by fushar** [comment]
Hmm bisa gini gak ya?

(Warning: ini cuma coret-coret asal, tapi harusnya dapat idenya)

    all: $(SRC)
        for tex in $?; do
            (cd <base folder si tex>; latexmk -pdf -pdflatex="pdflatex -interactive=nonstopmode" -use-make <nama file si tex>)
        done

**Comment by gyosh** [comment]
@petrabarus lol bisa
oke dicoba dulu ya, mestinya udah beres sih masalahnya
