### ISSUE TITLE
bab 9 array D dan E

### ISSUE THREAD

**Issue by amirul17** [ia-toki/training-gate-id#111]
saat saya coba selalu salah, padahal menurut saya jawaban saya benar

**Comment by gyosh** [comment]
@amirul17 bisa tolong diperjelas? Untuk topik apa? Pemrograman dasar atau pemrograman kompetitif dasar?
Bisa cantumkan kode Anda juga?

**Comment by amirul17** [comment]
pemrograman dasar,
ID soal D : 89989
ID soal E : 89990

**Comment by gyosh** [comment]
@amirul17 Kasus uji untuk kedua soal baik-baik saja.
Untuk perkalian matriks, ada perbaikan untuk penjelasan rumusnya.

Mungkin untuk memperjelas, bisa tolong cantumkan kode kamu?

**Comment by amirul17** [comment]
kode yang mana? program saya yang salah bagian mana?

**Comment by gyosh** [comment]
@amirul17 Oh ternyata

> ID soal D : 89989
> ID soal E : 89990

Maksudnya adalah ID submission untuk soal D dan E.
Untuk kedua solusi tersebut, ada kelebihan spasi di pada saat output solusi.

Silakan diperbaiki dulu.
Isu ini saya tutup karena tidak ada kesalahan pada kasus uji.
