### ISSUE TITLE
TLX PC CompFest 2011 - Penyisihan Mahasiswa

### ISSUE THREAD

**Issue by blank217** [ia-toki/training-gate-id#113]
saya submit WA, sampe testcase sample juga WA

https://training.ia-toki.org/problemsets/23/problems/120/
http://ideone.com/ke7tjL

**Comment by gyosh** [comment]
Isu yang dilaporkan hanya bisa berupa isu terkait soal training gate
Untuk masalah ini, silakan lapor di https://forum.ia-toki.org/ atau di grup Facebook Olimpiade Informatika Indonesia.

**Comment by alijaya** [comment]
tolong dipindah ke sini untuk soal selain Training Gate https://github.com/ia-toki/Training-TLX
