### ISSUE TITLE
BAB 9 Array C Pemrograman Dasar

### ISSUE THREAD

**Issue by firmanmm** [ia-toki/training-gate-id#115]
kenapa saat saya unggah selalu salah. Sedangkan jika dijalankan secara manual hasilnya sama persis.Bab 9 Array Prob C Submission ID 94978.
Terima Kasih atas bantuannya

[Array.zip](https://github.com/ia-toki/training-gate-id/files/322329/Array.zip)

**Comment by alijaya** [comment]
Kalau inputannya
4
1 1 1000 1000

jawabannya apa? Apakah Arraynya kurang gede?
