### ISSUE TITLE
BAB 9 Array C Pemrograman Dasar

### ISSUE THREAD

**Issue by firmanmm** [ia-toki/training-gate-id#116]
Mohon maaf sebelumnya jika membuat issues baru. Tetapi saya masih memiliki masalah yang sama. Mungkin pertanyaan saya sebelumnya kurang lengkap. Kode saya sudah saya perbaiki tetapi masih mendapati kesalahan yang sama persis.

BAB 9 Array C Pemrograman Dasar. Submission ID 96853. 
Yang menjadi pertanyaan saya adalah, Mengapa saya mendapat **Wrong Answer dengan nilai total 0**. Dan juga saya sudah mencoba memasukkan input dari _data sample_ dan mendapatkan **output yang sama persis ** dengan data sample. Akan tetapi saya mendapat  **Wrong Answer** untuk **data sample**. Saya sudah mencobanya di Codechef dan saya sudah menyertakan buktinya dan kode saya dibawah ini.
Dan juga untuk :
> 
> Kalau inputannya
> 4
> 1 1 1000 1000
> 
> jawabannya apa? Apakah Arraynya kurang gede?

Sudah saya perbaharui dan menghasilkan output sesuai gambar dibawah. Terimakasih atas sarannya.

> NB: Batasan:
> 1<N<100.000
> **1**<**SetiapBilBulat Pada baris ke 2**<**1000**
> Mohon bantuannya, terima kasih.

![screenshot_fri_jun_24_22 02 20](https://cloud.githubusercontent.com/assets/20027378/16341746/e81d5f3e-3a58-11e6-90cd-e2d87f41c107.png)

![screenshot_fri_jun_24_22 03 45](https://cloud.githubusercontent.com/assets/20027378/16341683/99d75a82-3a58-11e6-9df4-bd1836210058.png)
![screenshot_fri_jun_24_22 05 23](https://cloud.githubusercontent.com/assets/20027378/16341684/99e54c32-3a58-11e6-98f5-95abb9c1cc72.png)
![screenshot_fri_jun_24_22 06 19](https://cloud.githubusercontent.com/assets/20027378/16341685/9aea2990-3a58-11e6-9a93-1bfe5d5bfb1a.png)

[ArrayNewVer.zip](https://github.com/ia-toki/training-gate-id/files/331959/ArrayNewVer.zip)

**Comment by gyosh** [comment]
Kamu mengakses `Counter[2000]`
Array `Counter` yg terdefinisi dari elemen berapa sampai berapa?
Ini bikin komputer bingung trus dia bertindak ga jelas.
