### ISSUE TITLE
Ch 3: Kuis Ekspresi dan Masukan/Keluaran, Soal #12

### ISSUE THREAD

**Issue by seffendy** [ia-toki/training-gate-id#117]
Soal #12:

Diberikan dua buah pecahan a/b dan c/d. Jika variabel pembilang1 dan penyebut1 mendefinisikan a dan b, serta pembilang2 dan penyebut2 mendefinisikan c dan d, maka ekspresi yang tepat untuk membandingkan apakah a/b sama dengan c/d adalah ....

a (pembilang1/penyebut1) = (pembilang2/penyebut2)
b (pembilang1 div penyebut1) = (pembilang2 div penyebut2)
c pembilang1 * penyebut2 = pembilang2 * penyebut1
d pembilang1 * pembilang2 = penyebut1 * penyebut2
e terdapat lebih dari satu jawaban yang tepat

Ini kenapa pilihan (a) salah ya?

http://wiki.freepascal.org/Assignment_and_Operations

Anw, jawaban di grader (c), bukan (e).

**Comment by gyosh** [comment]
Karena pilihan (a) berisiko precision error, jadi dianggap tidak tepat.

**Comment by seffendy** [comment]
Kalau gitu gw challenge: pilihan (c) berisiko overflow.

Dan, di chapter ini memangnya mereka udah belajar tentang presisi? Judul bab nya masih tentang IO, dan gw quick-search di pdf nya, ngga ada yang membahas ini. Apa ini nggak membuat mereka jadi bertanya-tanya (nggak ada penjelasan gitu)?

**Comment by gyosh** [comment]
Presisi ada dijelasin di bab sebelumnya, walaupun ngga dinyatakan eksplisit kalo 
```
2.999999999999 != 3.0000000000
```
Berhubung ini bab tentang ekspresi juga, makanya ditanyain.

Solusi yg diajukan: soal diperjelas dengan kasih tau constraint, dan di pdf dikasih tau eksplisit kalo komparasi dengan `=` pada floating point berisiko precision error.

**Comment by seffendy** [comment]
Ah, setuju.

**Comment by gyosh** [comment]
Baik, terima kasih atas laporannya :heart:
