### ISSUE TITLE
Ch 3: Kuis Ekspresi dan Masukan/Keluaran, Soal #3

### ISSUE THREAD

**Issue by seffendy** [ia-toki/training-gate-id#118]
Soal #3
 	
Perhatikan program berikut:

```
var
    b1, b2, jml: longint;
begin
    b1 := 2000000000;
    b2 := 2000000000;

    jml := (b1 + b2) mod 123;
    writeln(jml);
end.
```

Yang terjadi jika program tersebut dijalankan adalah ....

a tercetak 25
b terjadi overflow
c terjadi underflow
d tidak bisa dijalankan karena program tidak bisa dikompilasi
e terjadi error selain overflow dan underflow

Di sini gw expect jawabannya (b) overflow, tapi barusan gw coba di FreePascal 2.60 di Windows gw, ternyata outputnya 25. Kemudian gw test di ideone.com (FPC), outputnya -12 (overflow), tapi kalau dicompile dengan GPC (GNU Pascal, ideone juga), outputnya 25 juga.

FPC: http://ideone.com/PDtVxk (output -12)
GPC: http://ideone.com/I1e4Nh (output 25)

GPC keliatannya ada fitur auto-promote u/ kasus seperti ini.

Gw rasa kasus ini jadi spesifik ke compiler dan nggak standard (sama seperti masalah evaluasi operator ++ di C/C++). Mungkin perlu dipertimbangkan untuk mengubah atau memperbaiki soalnya.

**Comment by gyosh** [comment]
Solusi yg diajukan: dikasih tau kalo menggunakan compiler FPC.
Gimana?

**Comment by seffendy** [comment]
Nggak bisa. Compiler yang gw pake: FPC 2.60 (Windows), dan outputnya 25 (nggak overflow).

**Comment by gyosh** [comment]
Hmm repot juga, pengen kasih pelajaran tentang overflow malah compilernya kepo :sweat: 

Solusi yg diajukan:
Soal diganti jadi kita kasih tau, kalo itu dijalanin, hasilnya -12. Pertanyaannya adalah kenapa demikian.
Lalu pilihan jawabannya:

a operator modulo menjadi tidak akurat ketika salah satu operand mencapai nilai milyaran   
b terjadi overflow saat penjumlahan b1 dengan b2
c terjadi underflow saat penjumlahan b1 dengan b2
d angka 123 sebagai salah satu operand tidak memiliki tipe data yang jelas
e terjadi error selain overflow dan underflow

**Comment by seffendy** [comment]
OK, setuju.

Anw, ya itu emang bukan tentang standard.

**Comment by gyosh** [comment]
Baik, terima kasih atas laporannya :heart:

**Comment by gyosh** [comment]
Deskripsi soal sudah diubah.
