### ISSUE TITLE
Ch 4: Kuis Penunjang Pemrograman Dasar, Soal #2

### ISSUE THREAD

**Issue by seffendy** [ia-toki/training-gate-id#120]
Soal #2 

Berikut ini adalah beberapa pernyataan:

I. Compile error pasti terjadi sebelum runtime error.
II. Program yang tidak mendapat compile error, pasti tidak mendapat runtime error.
III. Range check error termasuk ke dalam compilation error.
IV. Selama terdapat warning dari kompilator Free Pascal, program tidak dapat dieksekusi.

Di antara keempat pernyataan tersebut, pernyataan yang bernilai benar adalah ....

a hanya I
b hanya II dan III
c hanya II dan IV
d hanya III dan IV
e hanya II, III, dan IV

Soal ini di TLX jawabannya (a).

Tapi coba dipikir lagi point (I) di atas. Kalimat (I) imply kalau ada satu alur eksekusi program di mana Compile Error terjadi sebelum Runtime Error (ada CE dan diikuti oleh RTE di satu alur itu). Dan kalau kita melihat dari versi strict-nya, kalimat (I) itu imply bahwa semua RTE pasti diawali dengan CE. Well, nangkep kan maksudnya.

Intinya, kalimat (I) perlu diperbaiki.

**Comment by gyosh** [comment]
Solusi yang digunakan adalah kalimat (I) diganti jadi:

> Jika runtime error, maka compile error tidak terjadi
