### ISSUE TITLE
Ch 1: Perkenalan Pemrograman Kompetitif, Soal #A Seleksi Olimpiade

### ISSUE THREAD

**Issue by nmfzone** [ia-toki/training-gate-id#122]
Sepertinya TestCase yang ada di soal ini kurang variatif / kurang banyak.

Karena saya menggunakan cara seperti ini saja 

`A+(B*3)+(C*5)`

bisa **AC**. Maksudnya saya melakukan operasi tsb pada nilai peserta, kemudian sorting berdasarkan hasil akhirnya. Misalnya saja sesuai sample test case, maka hasilnya : 

```
P0002 1000
P0001 810
P0003 801

Hasil : TIDAK
```

Padahal harusnya cara diatas akan **WA** ketika test casenya (misal) :

```
3 1
P0001
P0001 10 1000 199
P0002 0 0 200
P0003 1 100 100

Hasil : YA (padahal seharusnya TIDAK)
```

Maaf kalau penjelasannya membingungkan :stuck_out_tongue_closed_eyes:

**Comment by gyosh** [comment]
Terima kasih atas laporannya, akan segera diperbaiki :grinning:

**Comment by gyosh** [comment]
Sudah diperkuat TC nya, maaf lama
