### ISSUE TITLE
TC Perkalian matriks bebek kurang variatif

### ISSUE THREAD

**Issue by thegalang** [ia-toki/training-gate-id#123]
jadi untuk pertanyaan tipe 2, tidak ada TC yang outputnya lebih besar dari 1, jadi untuk pertanyaan kedua, kita bisa saja print 1 terus,

contoh:
3
5 5 5 5
2

harusnya kan banyaknya cara:
(A x B) x C
A x (B x C)
ada sebanyak 2 cara,

tetapi kalau kita print 1, akan mendapatkan AC di soalnya

**Comment by gyosh** [comment]
Sudah diperkuat TC nya, terima kasih atas masukannya
