### ISSUE TITLE
noob wanna ask (floor ciel) 

### ISSUE THREAD

**Issue by isfahany** [ia-toki/training-gate-id#124]
saya sudah cukup paham dengan teori floor dan ciel
saya sudah coba nge program bagian program dasar percabangan problem floor ciel dari jam 6 pagi
namun program aneh yang pertama tama saya buat dapat scoring 80 dan program yang secara teori matematika benar hanya sampai nilai 50.
saya juga masih kurang paham dengan verdict, id, dsb
tolong bantu saya karena saya sangat berminat untuk mendalami bahasa pemograman..

**Comment by alijaya** [comment]
Halo,

Untuk pertanyaan seperti ini, bisa ditanyakan di Group Facebook saja.
Tapi untuk hint soal ini... Pastikan untuk bilangam negatif benar, dan
floor dan ceil bilangan bulat juga benar.

Salam,
Ali
