### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by alifraher** [ia-toki/training-gate-id#126]
Assalamuailakum,

Saya ada beberapa masalah dengan soal-soal di toki seperti:

Pemrograman Dasar
Chapter 12, D. Pendataan Berat Bebek
http://ideone.com/e.js/XEkVec

Pemrograman Kompetitif Dasar
Chapter 1, A. Seleksi Olimpiade
http://ideone.com/e.js/AvEc4B

Chapter 1, D, Hapus Satu Saja
http://ideone.com/e.js/EmIYIy

Saya udah coba beberapa test case pada masing-masing soal tersebut dan hasilnya baik-baik saja. Tetapi kenapa saat saya upload hasilnya ada submission yang Runtime Error.

Mohon diperiksa kembali apakah ada kesalahan pada program saya.

Terima Kasih

**Comment by gyosh** [comment]
@alifraher coba gunakan nama class Main untuk setiap solusi tersebut

**Comment by gyosh** [comment]
Isunya sudah kadaluarsa, silakan buka isu kembali bila masih dirasa ada kesalahan pada sistem
