### ISSUE TITLE
Ch. 4D Soal Tambahan, I - Pesta Bebek : case insensitive? (soal ambigu)

### ISSUE THREAD

**Issue by seffendy** [ia-toki/training-gate-id#127]
Pada soal:

p1: "Daftar tersebut diurutkan berdasarkan urutan kamus tanpa membedakan huruf besar dan huruf kecil."
p2: "Tidak ada dua tamu yang hadir secara bersamaan dan tidak ada dua tamu yang memiliki nama sama persis."

Dari dua kalimat di atas, saya berasumsi tidak ada dua nama yang sama bahkan ketika case-insensitive, ct: ABC dan abc tidak akan muncul pada kasus yang sama.

Tapi keliatannya, ada 3 test case yang tidak demikian (ada dua nama yang sama yang muncul ketika case diabaikan).

Assert FALSE ketika ada nama yang sama = RTE
https://training.ia-toki.org/training/curriculums/2/courses/5/chapters/35/submissions/programming/122157

Untuk nama yang sama, ambil nomor urut terakhir (hilangin assert) = AC
https://training.ia-toki.org/training/curriculums/2/courses/5/chapters/35/submissions/programming/122158

Jadi, ini ada dua pilihan:
1. perbaiki test case, atau
2. perbaiki deskripsi soal (ditambah penjelasan tentang bagaimana nomor orang yang namanya sama).

**Comment by gyosh** [comment]
Pilihan solusi 2 akan digunakan

**Comment by gyosh** [comment]
Beres, terima kasih laporannya Pak @seffendy!
