### ISSUE TITLE
SOAL TOKI MODUS TERBESAR

### ISSUE THREAD

**Issue by adylanrff** [ia-toki/training-gate-id#128]
Code saya sudah pernah disubmit dengan akun lain, dan hasilnya nilainya 100, sedangkan saat diinput di akun saya nilainya hanya 50, mohon bantuannya.

`program modus2;
var
  table : array [1..1001] of longint;
  t,a,b,c,r : longint;
begin
  readln(c);

  for a:= 1 to c do
  begin
    readln(b);
    table[b]:= table[b]+1;
  end;

  t:= -999;
  r:= -999;
  for a:= 1000 downto 1 do
  begin
    if(table[a]>t) then
    begin
      t:= table[a];
      r:=a;
    end;
  end;
  write(r);
  writeln();
end.`

[Modus.txt](https://github.com/ia-toki/training-gate-id/files/541964/Modus.txt)

**Comment by gyosh** [comment]
@adylanrff Untuk pertanyaan seperti ini, harap menggunakan forum atau grup olimpiade informatika
