### ISSUE TITLE
Java compiler luas segitiga

### ISSUE THREAD

**Issue by Noob321** [ia-toki/training-gate-id#129]
Permisi gan mau tanya, saya mencoba luas segitiga menggunakan java tapi hasilnya compile error padahal compiler ane sendiri sudah jalan, ini programnya:

import java.util.Scanner;
class luas {
    public static void main(String[] okee) {
        Scanner input= new Scanner(System.in);
        int A= input.nextInt();
        int T= input.nextInt();
        double hasil= (double)A*T/2;
        System.out.printf("%.2f",hasil);
    }
}

program yang sebelumnya pake pascal ataupun c gk masalah pas pake java jadinya compile error

**Comment by gyosh** [comment]
Coba gunakan nama class "Main"

**Comment by Noob321** [comment]
oh iya mas maaf bukan compile error tapi wrong answer,, padahal saya sudah coba macam macam cara pembuatan  2 desimal dibelakang komanya tapi tetap wrong answer dan nilainya selalu 0, apakah ada clue untuk untuk statement yang ditambahkan, terakhir kali program yg saya coba ini mas, 

import java.text.DecimalFormat;
import java.util.Scanner;

class Main {

    public static void main(String[] args) {
        Scanner input= new Scanner(System.in);
        DecimalFormat df= new DecimalFormat(".##");
        int A= input.nextInt();
        int T= input.nextInt();
        float hasil= (float) A*T/2;
        String hasil_akhir= (df.format(hasil));
        double baru= Double.parseDouble(hasil_akhir);
        System.out.print(baru);
    }
}
 
tapi masih tetep wrong answer

**Comment by fushar** [comment]
Gunakan `println()`, bukan `print()`.

**Comment by Noob321** [comment]
Sudah saya coba, masih wrong answer

**Comment by gyosh** [comment]
@Noob321 kalau masalahnya adalah wrong answer, harap menggunakan forum/grup olimpiade informatika Indonesia.
