### ISSUE TITLE
Tanggal rilis, versi, dan publikasi

### ISSUE THREAD

**Issue by dragoon20** [ia-toki/training-gate-id#13]
Ini bagaimana ya enaknya waktu rilis dan publikasinya? Atau jangan-jangan sudah dirilis namun belum dipublikasi? Apakah menggunakan versi (misal 1.0.0)?

**Comment by gyosh** [comment]
Sebenarnya belum rilis, karena masih ada materi yang belum selesai
Jika sudah ada versi yang *stable*, maka akan dirilis versi 1.0 :)

**Comment by gyosh** [comment]
Setelah didiskusikan bersama @dragoon20 dan @fushar, diputuskan untuk menggunakan [semantic versioning 2](http://semver.org/). Secara singkat, format versi adalah <major>.<minor>.<patch> dengan ketentuan:

1. Setiap perubahan mayor seperti penambahan course baru, akan menambah <major>
2. Setiap perubahan minor seperti penambahan slide baru, akan menambah <minor>
3. Setiap perubahan yang sifatnya bugfix, perbaikan kalimat, dsb, akan menambah <patch>

Commit pada branch master yang memajukan versi akan diberikan tag, sehingga dokumen versi-versi sebelumnya juga bisa digunakan.

**Comment by fushar** [comment]
Ditutup karena pertanyaan sudah terjawab.
