### ISSUE TITLE
Pemrograman Dasar - Chapter 6 Perulangan - Soal B for

### ISSUE THREAD

**Issue by mochadwi** [ia-toki/training-gate-id#130]
Please kindly check, I always fail submit my program?

I'm using Pascal language, and check for other person submission a year ago.

Or maybe, is there any future plan to show the *test data* number?

**Comment by gyosh** [comment]
@mochadwi

1. Could you provide your submission id? Or attach the source code
2. There is no future plan to show test data number

**Comment by gyosh** [comment]
Stalled issue, please reopen if problem still exists
