### ISSUE TITLE
Sample Test Case Bab 4. DnC

### ISSUE THREAD

**Issue by Andrewfang21** [ia-toki/training-gate-id#131]
Saat saya run di C++, programnya ngeluarin output sesuai dengan sample outputnya.. Tapi pas di submit, katanya sample test WA. Mohon dicek.. trims

(https://cloud.githubusercontent.com/assets/21152574/21082118/1a6742aa-c007-11e6-927e-a16b65161647.png)

**Comment by gyosh** [comment]
@Andrewfang21 Bisa minta submission id supaya kodenya bisa diperiksa?
Pastikan tidak ada kelebihan spasi atau newline di akhir

**Comment by gyosh** [comment]
Stalled issue, harap buka kembali jika masih menjadi masalah
