### ISSUE TITLE
Chapter 3 Brute Force : soal Jawbreaker 4 : Tc kurang kuat

### ISSUE THREAD

**Issue by thegalang** [ia-toki/training-gate-id#132]
dalam permainan jawbreaker, apabila jumlah angka dalam sebuah rangkaian cuman 1, rangkaian tersebut tidak boleh diambil. contoh:
4 5
3 3 1 3 3
1 1 2 1 1
1 1 3 1 1
1 1 4 1 1
seharusnya jawabannya 60, karena kita tidak boleh mengambil angka 2, 3, 4 yang ada di bawah, tetapi program yang memprint 156 akan mendapat AC

**Comment by gyosh** [comment]
Terima kasih atas laporannya. Testcase sudah diperkuat.

Untuk berikutnya harap melaporkan isu yg berkaitan dengan soal di https://github.com/ia-toki/Training-TLX
