### ISSUE TITLE
Masalah bahasa default

### ISSUE THREAD

**Issue by thegalang** [ia-toki/training-gate-id#133]
untuk semua soal, apabila kita ingin mensubmit, kelihatan bahwa bahasa yang pertama terpilih adalah C++11, mungkin ini tidak mengganggu bagi pengguna C++, tapi ada juga pengguna pascal, java, dll yang merasa sedikit terganggu harus mengubah pilihan bahasa setiap mau submit

jadi saran: setting pilihan bahasa default menjadi bahasa terakhir yang kita pakai submit

**Comment by gyosh** [comment]
Karena ini issue tentang judgels, maka sebaiknya dilaporkan ke https://github.com/judgels/judgels
