### ISSUE TITLE
Divide and Conquer: Kesalahan Ilustrasi Merge Sort

### ISSUE THREAD

**Issue by wirabdillah** [ia-toki/training-gate-id#134]
Pada halaman 11 slide tersebut, hasil merge array [7] dan [6] seharusnya menjadi [6, 7] akan tetapi pada slide menjadi [7, 6]. Hasil merge yang salah juga ada pada halaman 12.

https://github.com/ia-toki/training-gate-id/blob/master/topik/pemrograman-kompetitif-dasar/04-divide-and-conquer/pemrograman-kompetitif-dasar_04-divide-and-conquer.tex#L108

https://github.com/ia-toki/training-gate-id/blob/master/topik/pemrograman-kompetitif-dasar/04-divide-and-conquer/pemrograman-kompetitif-dasar_04-divide-and-conquer.tex#L117

**Comment by gyosh** [comment]
@wirabdillah terima kasih atas laporan ini :)
Sudah diperbaiki
