### ISSUE TITLE
Chapter 6 - Perulangan - Problem Pola I

### ISSUE THREAD

**Issue by alphamonouryuken** [ia-toki/training-gate-id#135]
Selalu Wrong Answer padahal coba run sendiri jawabannya bener, pas di tes di sitenya semuanya Wrong Answer

var
	n,m,i:integer;
begin
	readln(n,m);
        for i:= 1 to n-1 do
            if i mod m <> 0 then write(i,' ') else write('* ');
            if n mod m <> 0 then write(n) else write('*');
        readln();
end.

**Comment by gyosh** [comment]
Jangan gunakan readln pada akhir program

**Comment by gyosh** [comment]
Stale issue, closing
