### ISSUE TITLE
Chapter 1 Perkenalan Pemrograman Kompetitif : Soal C (wildcards)

### ISSUE THREAD

**Issue by Bennywj** [ia-toki/training-gate-id#136]
apa mungkin ada testcase dimana pattern lebih panjang dari string?
kalau memang benar ada itu jadinya kek gimana?

**Comment by gyosh** [comment]
Mungkin
Cukup cetak string yang memenuhi pattern
Kalau tidak ada, berarti tidak perlu mencetak apa-apa
