### ISSUE TITLE
Ambil referensi dari buku? 

### ISSUE THREAD

**Issue by KerenzaDoxolodeo** [ia-toki/training-gate-id#14]
Mau nanya. Apakah boleh kita ambil referensi dari buku atau internet. Contohnya merge sort itu kan ada di Introduction to Algorithm. Boleh gak kita mungkin nulis materi ambil dari situ. Kalo boleh bagaimana cara kredit nya? (eg: Daftar pustaka)

**Comment by gyosh** [comment]
boleh, dengan catatan:

1. Hindari plagiarisme dengan tidak sekadar mengutip/menerjemahkan penjelasan yang berasal dari sumber tersebut
2. Menuliskan sumber pada bagian daftar pustaka, pada bagian akhir slide. Format penulisan daftar pustaka bisa dengan cara yang biasa: "<nama penulis>. <tahun terbit>. <judul cetak miring>. <kota penerbit>:<penerbit>"

**Comment by fushar** [comment]
Ditutup karena pertanyaan sudah terjawab.
