### ISSUE TITLE
Submission: Rekrusif Dasar

### ISSUE THREAD

**Issue by KerenzaDoxolodeo** [ia-toki/training-gate-id#15]
Jujur saya masih agak nggak mudeng dengan cara kerja kontribusi tapi ini dia.
Latex: http://pastebin.com/QaWai8Mv
Aset (1 file): http://i.imgur.com/JEMLX1S.png

**Comment by gyosh** [comment]
Mantap teman
Saya sudah baca-baca. Ada beberapa yang typo dan perlu diperbaiki sih, tapi itu urusan belakangan.
Sekarang, apakah Anda sudah pernah menggunakan git dan familiar dengan operasi seperti add, commit, push?

**Comment by KerenzaDoxolodeo** [comment]
Sayangnya tidak. :(

**Comment by gyosh** [comment]
Baik, tidak masalah.
Coba mainkan dulu https://try.github.io/levels/1/challenges/1
Setelah itu, coba untuk clone repository ini ke komputer Anda, lalu kabari lagi.

**Comment by KerenzaDoxolodeo** [comment]
Baik. Saya akan coba. Tapi ada UTS jadi ini mungkin harus menunggu dulu :)
