### ISSUE TITLE
Kelas Pembelajaran Pemrograman - Pemrograman Kompetitif Dasar - Perkenalan - Problem Wildcard

### ISSUE THREAD

**Issue by wibitwibit** [ia-toki/training-gate-id#155]
Saya menggunakan .compare (milik String C++) mengapa WA terus di TC ke 2 ya (maksimal hanya mendapat total nilai 90) ?

padahal sudah dicoba semua kemungkinan TC mengingat kemungkinan nya tidak banyak. Atau bolehkah mendapat bocoran testcase (TC) nomor 2? 

Terima kasih

**Comment by gyosh** [comment]
tidak ada kesalahan pada test case, dan mohon maaf karena tidak boleh mendapatkan bocoran test case.
disarankan supaya berdiskusi di grup facebook tentang implementasi solusinya.

**Comment by wibitwibit** [comment]
ow y baik, terima kasih ya

**Comment by wibitwibit** [comment]
group FB nya dimana ya? terima kasih

**Comment by gyosh** [comment]
bisa ke sini ya https://www.facebook.com/groups/olimpinfo
