### ISSUE TITLE
Penggunaan Notepad++

### ISSUE THREAD

**Issue by fairuzi10** [ia-toki/training-gate-id#159]
Slide perkenalan seakan menganjurkan penggunaan Notepad++ dibanding Dev C++ dengan alasan Notepad++ cukup populer. Menurut saya, lebih baik menggunakan Dev C++ saja karena lebih mudah dalam kompilasi dan sangat banyak anak yang menggunakan Dev C++. Selain itu, mengajarkan penggunaan cmd di awal saya rasa memberatkan padahal sangat jarang digunakan seperti pada soal output only yang saat ini belum masuk materi PD. Penggunaan Dev C++ juga lebih mirip dengan Geany, IDE yang digunakan saat OSN yang saat ini menggunakan Linux (tidak ada notepad++).

**Comment by afaji** [comment]
hmm kayaknya boleh juga kita fokus ke dev c++..

Ini siapa jadinya yg mau bikin wqwqwqw

@fairuzi10 @gyosh

**Comment by fairuzi10** [comment]
Jadinya mau pakai dev C++?

**Comment by fushar** [comment]
Slide Perkenalan sudah menggunakan Dev C++.
