### ISSUE TITLE
CH:6 Perulangan Pola 1

### ISSUE THREAD

**Issue by trine342** [ia-toki/training-gate-id#161]
ada yang bisa bantu knp wrong answer melulu?? 
var a,b,c:byte;
begin
read(a);
readln(b);
for c:=1 to a do begin
if c mod b = 0 then write('* ')
else write(c,' ');
end;
end.
padahal input sama ouputnya bener??

**Comment by fairuzi10** [comment]
Program kamu akan menghasilkan spasi di akhir keluaran. Jika spasi = _, maka untuk a = 4 dan b = 2 program kamu mengeluarkan
1_*_3_*_
Sedangkan TLX hanya menerima jawaban yang sama persis, termasuk spasi, yaitu
1_*_3_*

**Comment by trine342** [comment]
udah dibenerin gini tpi ttp wrong answer
var a,b,c:byte;
begin
read(a);
readln(b);
for c:=1 to a-1 do begin
if (c mod b <> 0) then write(c,' ') else write('* ');
end;
if (a mod b <> 0) then write(c) else write('*');
end.
gmn ya kak?

**Comment by fairuzi10** [comment]
Pada akhir selalu print \n. Dengan kata lain, gunakan writeln pada operasi tulis terakhir
