### ISSUE TITLE
Chapter 07: Dynamic Programming. Knapsack

### ISSUE THREAD

**Issue by nirvanasm** [ia-toki/training-gate-id#165]
Pada soal disebutkan

> Cetak nomor batu-batu yang perlu dibawa supaya total harga jualnya maksimal dan total beratnya tidak lebih dari N, satu nomor pada satu baris. Cetak nomor-nomor ini terurut dari kecil ke besar.  
> 
> Jika ada lebih dari satu cara pengambilan batu yang optimal, cetak cara pengambilan batu yang meminimalkan beratnya.
> 
> Jika masih ada lebih dari satu cara, utamakan batu dengan nomor lebih kecil.

Namun pada testcase belum terdapat corner case untuk kasus dimana pengambilan batu yang meminimalkan berat. Berikut salah satu contoh case yang membutuhkan kasus ke-2 (minimal berat)

Input ::
30 3
15 1
10 2
24 3

Ouput ::
3

**Comment by gyosh** [comment]
Ok test case sudah ditambahkan. Terima kasih atas masukannya!

**Comment by Fariz36** [comment]
Sepertinya testcase yang mengutamakan pengambilan batu dengan nomor terkecil masing kurang kuat
Input ::
6 3
2 10
6 20
4 10
Output ::
1 3
