### ISSUE TITLE
Course 2 - Chapter 3 - E. Pertemuan Pak Dengklek (Runtime Error)

### ISSUE THREAD

**Issue by dimasarna** [ia-toki/training-gate-id#166]
Terdapat masalah verdict runtime error padahal di terminal berjalan dengan baik.
Berikut lampiran codenya : [link](https://pastebin.com/RMEULUyx)

**Comment by fairuzi10** [comment]
Kode yang berjalan di lokal belum tentu dapat berjalan di TLX dengan hasil yang sama, terutama jika diuji dengan kasus uji yang berbeda. Jika fungsi std::basic_string::swap diganti dengan std::swap, maka akan mendapat accepted. Silakan cari tahu penyebabnya dengan mendalami cara kerja std::basic_string::swap terutama jika bermain dengan pointer.

**Comment by dimasarna** [comment]
Terimakasih atas bantuannya, nanti akan saya pelajari lagi lebih lanjut.
