### ISSUE TITLE
Materi Variabel Tipe Data String tidak muncul pada TLX

### ISSUE THREAD

**Issue by hashlash** [ia-toki/training-gate-id#178]
Pada source code terdapat materi [Variabel dan Tipe Data: String](https://github.com/ia-toki/training-gate-id/blob/master/topik/pemrograman-dasar-cpp/02-variabel-tipe-data/pemrograman-dasar-cpp_02-variabel-tipe-data-string.tex), namun tidak muncul pada [course di TLX](https://tlx.toki.id/courses/basic/chapters/02/lessons).

**Comment by fushar** [comment]
Course tersebut sudah tidak dikembangkan lagi.
