### ISSUE TITLE
Chapter 07: Dynamic Programming. Knapsack

### ISSUE THREAD

**Issue by Fariz36** [ia-toki/training-gate-id#182]
Sepertinya testcase yang mengutamakan pengambilan batu dengan nomor terkecil masing kurang kuat
Input ::
6 3
2 10
6 20
4 10
Output ::
1 3

Code saya yang saya submit 2 tahun yang lalu memberikan output "2", akan tetapi AC

**Comment by prabowo02** [comment]
Kasus uji tersebut sudah ditambahkan, terima kasih atas laporannya
