### ISSUE TITLE
[Soal] Pemrograman Kompetitif Dasar 07 A. Uang Kembalian

### ISSUE THREAD

**Issue by JoelGunawan** [ia-toki/training-gate-id#184]
Terdapat test case lemah pada soal, sehingga tidak ada test case yang menghasilkan banyak koin invalid (output -1).
Berikut merupakan contoh solusi salah yang berhasil lolos test case soal ini:
https://tlx.toki.id/courses/competitive/chapters/07/problems/A/submissions/1730319

**Comment by fushar** [comment]
Terima kasih, sudah diperbaiki.

FYI, soal sudah berubah URL ke: https://tlx.toki.id/courses/competitive-1/chapters/07/problems/A.
