### ISSUE TITLE
Rekursi Lanjutan

### ISSUE THREAD

**Issue by gyosh** [ia-toki/training-gate-id#23]
Butuh pengembangan materi sesuai petunjuk yang ditulis pada slide (cek materi_10_2 pada https://www.dropbox.com/sh/9v7anrmpd7rr6qz/AAA1tiAqBNinWl7LJ5dR9c01a?dl=0)

**Comment by fariskhi** [comment]
Saya akan coba untuk melengkapinya

**Comment by gyosh** [comment]
Baik, silakan lakukan :+1:

**Comment by fariskhi** [comment]
Sepertinya penjelasan tentang fibonacci sendiri sudah cukup memakan halaman slide (12 halaman sendiri untuk fibonacci) seperti yang bisa dilihat di pull request saya. Penjelasan tentang permutasi juga pastinya cukup memakan halaman. Tidak apa-apakah jika jumlah total slidenya nanti sekitar 30?

**Comment by gyosh** [comment]
@fariskhi Ya, tidak masalah. Jika nantinya dirasa terlalu panjang untuk suatu slide, materinya bisa dipecah sebagai isu yang baru.
