### ISSUE TITLE
QuickSort

### ISSUE THREAD

**Issue by gyosh** [ia-toki/training-gate-id#25]
Butuh pengembangan materi sesuai petunjuk yang ditulis pada slide (cek materi_11_2 pada https://www.dropbox.com/sh/9v7anrmpd7rr6qz/AAA1tiAqBNinWl7LJ5dR9c01a?dl=0)\

Tambahan:

* Ganti Quick Sort menjadi QuickSort (pada README dan judul materi)

**Comment by fushar** [comment]
Sejauh yang saya tahu, khusus jenis sort ini, spelling yang benar itu "Quicksort" tanpa spasi. (Silakan dicek lagi juga.)

**Comment by gyosh** [comment]
Iya juga, oke sudah diperbaiki.

**Comment by gyosh** [comment]
Digabungkan ke #59
