### ISSUE TITLE
Spasi di sekeliling titik dua (':') pada deklarasi variabel

### ISSUE THREAD

**Issue by fushar** [ia-toki/training-gate-id#33]
Menurut saya, sebaiknya gaya ini yang digunakan:

    var a: longint;

ketimbang

    var a : longint;

Hal ini sesuai dengan banyak referensi yang saya temukan, contohnya: http://www.gnu-pascal.de/h-gpcs-en.html

**Comment by gyosh** [comment]
Setuju, segera diperbaiki
