### ISSUE TITLE
Tambah penjelasan tentang fungsi chr/ord untuk "Chapter 11: Pendalaman String"

### ISSUE THREAD

**Issue by matematikaadit** [ia-toki/training-gate-id#56]
Alangkah baiknya kalau dua fungsi ini juga dijelaskan. Banyak problem yang lebih simpel dikerjakan kalau menggunakan fungsi tersebut. Contohnya [Caesar Cipher](https://training.ia-toki.org/training/curriculums/1/courses/1/sessions/14/problems/53/).

**Comment by gyosh** [comment]
Kedua fungsi ini sebenarnya udah dijelaskan di [pemrograman-dasar_02-variabel-tipe-data](https://github.com/ia-toki/training-gate-id-pdf/raw/master/pemrograman-dasar_02-variabel-tipe-data.pdf).

Ok, ada baiknya ini diperdalam lagi di "Pendalaman String".
Terima kasih atas masukannya.

Oh ya, apakah @matematikaadit berminat untuk mengerjakannya?
