### ISSUE TITLE
Slide: Dynamic Programming

### ISSUE THREAD

**Issue by gyosh** [ia-toki/training-gate-id#61]
Tulis materi dynamic programming. Ini adalah tugas yang besar, dan tidak harus dikerjakan semuanya sekaligus. Pekerjaan dapat dicicil dan Anda boleh saja hanya mengerjakan sebagian.

Silakan mengikuti panduan konten yang diberikan (cek pemrograman-kompetitif-dasar_07-dynamic-programming.tex).
Anda boleh juga menambahkan konten di luar panduan, sesuai dengan persetujuan dan diskusi terlebih dahulu.

Bagi yang berminat untuk mengklaim tugas ini, silakan tinggalkan komentar.

**Comment by gyosh** [comment]
Saat ini diserahkan kepada @jonathanirvings

**Comment by gyosh** [comment]
Sebagian konten telah dikembangkan dan masuk ke master.
Masih ada bagian yang "todo", dan terbuka bagi yang berminat untuk pengerjaan.

**Comment by jonathanirvings** [comment]
*Nanggung*, saya sekalian coba selesaikan bagian "todo" nya. Sudah saya buat pull request.

**Comment by gyosh** [comment]
Aw yeah, terima kasih @jonathanirvings
Dengan masuknya #70 dan #73, issue ini ditutup.
