### ISSUE TITLE
Bahasa nama variabel pada kode sumber

### ISSUE THREAD

**Issue by fushar** [ia-toki/training-gate-id#71]
Sebaiknya seragam. Misalnya, jangan ada nama variabel `sudahDihitung` dan `isValid` dalam satu kode yang sama.

**Comment by gyosh** [comment]
@fushar apakah di master ada source code yg begini?
kalo di pull request, memang nanti akan diperbaiki

**Comment by fushar** [comment]
kayaknya sih nggak ada, ini gara-gara liat-liat seklias PR-PR sih

**Comment by gyosh** [comment]
Saya akan melaksanakannya.

**Comment by gyosh** [comment]
Sudah selesai, tersebar di banyak commit
