### ISSUE TITLE
Salah Testcase

### ISSUE THREAD

**Issue by apakaden** [ia-toki/training-gate-id#95]
https://training.ia-toki.org/training/curriculums/1/courses/11/sessions/55/problems/253/

Saya memiliki jawaban Accepted di tokilearning.org, namun Wrong Answer di TLX

**Comment by alijaya** [comment]
dilihat dulu ya ._.

**Comment by gyosh** [comment]
@alijaya apakah ada update? Kalo ngga, gua bisa coba cari tau
sayangnya link di atas rusak?

**Comment by fushar** [comment]
@gyosh link yang benar: https://training.ia-toki.org/training/curriculums/1/courses/11/chapters/55/problems/253/

**Comment by alijaya** [comment]
sudah dibenerin yang ini \ :v /
