### ISSUE TITLE
Chapter 6: Dynamic Programming, C. Penukaran Emas

### ISSUE THREAD

**Issue by alijaya** [ia-toki/training-gate-id#96]
Tanpa mensubmit apa2, nilai -1.23456789E9, dan warnanya hijau seakan2 sudah benar.
![voila_capture 2016-04-19_6-45-48_pm](https://cloud.githubusercontent.com/assets/74383/14637959/fdcfb8c8-065e-11e6-8a3c-d27951a974c9.png)

**Comment by prabowoD** [comment]
sama juga, belum submit apa2, nilainya -1.23456789E9
![untitled](https://cloud.githubusercontent.com/assets/18303489/14678642/25990806-0749-11e6-85fb-9342e0dcdc8d.png)

**Comment by fushar** [comment]
Sepertinya saya tahu kenapa. Apakah soal-soal tersebut terdapat pada lebih dari satu arsip/problemset?

**Comment by prabowoD** [comment]
ya, sepertinya soal-soal itu ada di tlc juga
tapi semuanya baru normal kembali setelah disubmit ulang

**Comment by alijaya** [comment]
@fushar: yap... di TLX yang baru sama di TLC migrasi

**Comment by fushar** [comment]
Oke sip, setidaknya bugnya sudah bisa teridentifikasi dan bisa di-reproduce, sedang dipikirkan solusinya :D

**Comment by alijaya** [comment]
sundul

**Comment by fushar** [comment]
Isu ini sudah tidak relevan.
