### ISSUE TITLE
Bab 6: Dynamic Programming. Soal Waterfall.

### ISSUE THREAD

**Issue by alvinpiter** [ia-toki/training-gate-id#97]
Sepertinya testcase #5 keliru. Mungkin ada koordinat batu yang lebih besar daripada V atau H. Solusi saya AC kalau selalu menganggap V = H = 500. CMIIW.

**Comment by alijaya** [comment]
sudah di cek... gak ada yang lebih dari 500 kok inputannya ._.

**Comment by alvinpiter** [comment]
Maksud saya bukan lebih dari 500. Misalnya gini, ukuran V = H = 5. Nah, nilai koordinat batunya ada yang lebih dari 5. Misalnya 1 1 6 6.

**Comment by prabowoD** [comment]
sepertinya ada yang aneh di testcase 3, 4, 5. 
Di soal tertulis "air selalu bisa mengalir"
tapi assertion ga lolos pas simulasiin jalanny air ._.

**Comment by alijaya** [comment]
._.

**Comment by prabowoD** [comment]
assertion ga lolos juga untuk tc 3, 4, 5.
`assert (v1 > 0 && v1 <= v);` 
`assert (v2 > 0 && v2 <= v);`
`assert (h1 > 0 && h1 <= h);`
`assert (h2 > 0 && h2 <= h);`

**Comment by alijaya** [comment]
untuk yang tc 5 gua dah cek... emang ada yang salah ._. mapnya kurang gede satu angka ==a, yang 3 sama 4 masih di cek

**Comment by alijaya** [comment]
yap bener yang tc 3 sama 4 juga salah ==a... dah diperbaikin... silahkan coba lagi :3

**Comment by prabowoD** [comment]
oke sip, thanks :D

**Comment by alijaya** [comment]
Ok ternyata masih ada salah lagi ==a... tadi aku cek... testcase 3, 4, 5 emang bermasalah, itu batunya ada yang dempet... jadi, aku remove aja itu TC ._., buat yang dah submit... submit ulang ya... ntah kenapa TLX ngebug UI nya jadi gak bisa batch regrade
